In [9]:
import pandas as pd
from google.cloud import bigquery

In [10]:
pd.set_option('display.max_columns', None)

In [11]:
# BigQuery configuration
project_id = "prj-qc-dev-qic"
# dataset_id = "ds_dev_qic_gold_qbrain"
bq_client = bigquery.Client(project=project_id)

In [33]:
sql =f"SELECT * FROM `prj-qc-dev-qic.ds_dev_qic_gold_qbrain.l1_admission`"
df = bq_client.query_and_wait(sql).to_dataframe(create_bqstorage_client=False)

In [34]:
df.shape

(23868, 17)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23868 entries, 0 to 23867
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ticket_id                  23860 non-null  object
 1   validate_result            23868 non-null  Int64
 2   usage_validate_date_time   15 non-null     datetime64[us]
 3   usage_group_quantity       23868 non-null  Int64
 4   usage_ticket_status        0 non-null      Int64
 5   usage_ingested_at          23868 non-null  datetime64[us, UTC]
 6   usage_type                 23868 non-null  Int64
 7   access_area_account_id     23868 non-null  object
 8   product_id                 23860 non-null  object
 9   ticket_ticket_status       23860 non-null  Int64
 10  ticket_validate_date_time  23851 non-null  datetime64[us]
 11  ticket_group_quantity      23860 non-null  Int64
 12  ticket_ingested_at         23860 non-null  datetime64[us, UTC]
 13  finance_group_tag_id       222 non-null    object
 14  tag_name                   222 non-null    object
 15  access_area_name           23868 non-null  object
 16  usage_type_name            23868 non-null  object
dtypes: Int64(6), datetime64[us, UTC](2), datetime64[us](2), object(7)
memory usage: 3.2+ MB

In [11]:
df.columns

Index(['ticket_id', 'validate_result', 'usage_validate_date_time',
       'usage_group_quantity', 'usage_ticket_status', 'usage_ingested_at',
       'usage_type', 'access_area_account_id', 'product_id',
       'ticket_ticket_status', 'ticket_validate_date_time',
       'ticket_group_quantity', 'ticket_ingested_at', 'finance_group_tag_id',
       'tag_name', 'access_area_name', 'usage_type_name'],
      dtype='object')

In [8]:
df["usage_type_name"].value_counts()

usage_type_name
Entry    23868
Name: count, dtype: int64

In [ ]:
["usage_ticket_status","usage_type","usage_validate_date_time"]

In [35]:
df=df.drop(["usage_ticket_status","usage_type","usage_validate_date_time"],axis=1)

In [36]:
df.sample(10)

,ticket_id,validate_result,usage_group_quantity,usage_ingested_at,access_area_account_id,product_id,ticket_ticket_status,ticket_validate_date_time,ticket_group_quantity,ticket_ingested_at,finance_group_tag_id,tag_name,access_area_name,usage_type_name
17845,38783010-5c34-16e2-1a29-019aa5ef8162,1,1,2026-01-01 16:54:52.806999+00:00,d368ba4c-9681-7fa9-4a6d-0198e56a8692,862747d7-f1e5-803d-0f9f-019aa229679a,110,2025-11-21 09:59:00,1,2026-01-01 16:54:12.507372+00:00,None,None,Six Flags General Admission,Entry
13779,c193316a-0bf4-cf12-29be-0199dd0128eb,1,1,2026-01-01 16:54:52.806999+00:00,6dd8155c-e847-8250-475e-0198e568646b,250e53ec-962d-25c7-64d9-0198e57b7414,110,2025-10-13 09:58:00,1,2026-01-01 16:53:42.330804+00:00,None,None,Six Flags Admission Dated,Entry
15307,58eea010-b0b3-5248-581f-019aa5a8cbfb,1,1,2026-01-01 16:54:52.806999+00:00,d368ba4c-9681-7fa9-4a6d-0198e56a8692,862747d7-f1e5-803d-0f9f-019aa229679a,110,2025-11-21 08:39:00,1,2026-01-01 16:54:12.507372+00:00,None,None,Six Flags General Admission,Entry
7607,768afdee-c633-dbae-6aa5-019aa71af26e,1,1,2026-01-01 16:54:52.806999+00:00,6dd8155c-e847-8250-475e-0198e568646b,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-21 15:49:00,1,2026-01-01 16:54:12.507372+00:00,None,None,Six Flags Admission Dated,Entry
9354,616c7e7f-253b-20b6-74ed-019ab206d6e1,1,1,2026-01-01 16:54:52.806999+00:00,6dd8155c-e847-8250-475e-0198e568646b,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-23 18:43:00,1,2026-01-01 16:54:12.507372+00:00,None,None,Six Flags Admission Dated,Entry
18667,bfd6dba6-52e9-b6d8-2c4d-019acc579156,1,1,2026-01-01 16:54:52.806999+00:00,d368ba4c-9681-7fa9-4a6d-0198e56a8692,862747d7-f1e5-803d-0f9f-019aa229679a,110,2025-11-28 21:21:00,1,2026-01-01 16:54:24.937928+00:00,None,None,Six Flags General Admission,Entry
17228,5413d1d6-0752-ee4f-016f-019aa5ef5cf3,1,1,2026-01-01 16:54:52.806999+00:00,d368ba4c-9681-7fa9-4a6d-0198e56a8692,862747d7-f1e5-803d-0f9f-019aa229679a,110,2025-11-21 09:59:00,1,2026-01-01 16:54:12.507372+00:00,None,None,Six Flags General Admission,Entry
9278,c203863a-e6e0-8737-1cf6-019ab1fb8abc,1,1,2026-01-01 16:54:52.806999+00:00,6dd8155c-e847-8250-475e-0198e568646b,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-23 18:31:00,1,2026-01-01 16:54:12.507372+00:00,None,None,Six Flags Admission Dated,Entry
14090,01b867c4-71bf-9e9d-58b7-019b30ef94c0,1,1,2026-01-01 16:54:52.806999+00:00,6dd8155c-e847-8250-475e-0198e568646b,250e53ec-962d-25c7-64d9-0198e57b7414,0,2025-12-18 10:09:00,1,2026-01-01 16:54:34.847494+00:00,None,None,Six Flags Admission Dated,Entry
3969,5837a879-093e-d9e2-044b-019a9d38123b,1,1,2026-01-01 16:54:52.806999+00:00,6dd8155c-e847-8250-475e-0198e568646b,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-19 17:45:00,1,2026-01-01 16:54:12.507372+00:00,None,None,Six Flags Admission Dated,Entry

In [15]:
df.shape

(23868, 14)

In [16]:
df.head()

,ticket_id,validate_result,usage_group_quantity,usage_ingested_at,access_area_account_id,product_id,ticket_ticket_status,ticket_validate_date_time,ticket_group_quantity,ticket_ingested_at,finance_group_tag_id,tag_name,access_area_name,usage_type_name
0,None,6,1,2026-01-01 16:54:52.806999+00:00,6dd8155c-e847-8250-475e-0198e568646b,None,<NA>,NaT,<NA>,NaT,None,None,Six Flags Admission Dated,Entry
1,None,6,1,2026-01-01 16:54:52.806999+00:00,6dd8155c-e847-8250-475e-0198e568646b,None,<NA>,NaT,<NA>,NaT,None,None,Six Flags Admission Dated,Entry
2,None,6,1,2026-01-01 16:54:52.806999+00:00,6dd8155c-e847-8250-475e-0198e568646b,None,<NA>,NaT,<NA>,NaT,None,None,Six Flags Admission Dated,Entry
3,None,6,1,2026-01-01 16:54:52.806999+00:00,6dd8155c-e847-8250-475e-0198e568646b,None,<NA>,NaT,<NA>,NaT,None,None,Six Flags Admission Dated,Entry
4,None,6,1,2026-01-01 16:54:52.806999+00:00,6dd8155c-e847-8250-475e-0198e568646b,None,<NA>,NaT,<NA>,NaT,None,None,Six Flags Admission Dated,Entry

In [17]:
df.columns

Index(['ticket_id', 'validate_result', 'usage_group_quantity',
       'usage_ingested_at', 'access_area_account_id', 'product_id',
       'ticket_ticket_status', 'ticket_validate_date_time',
       'ticket_group_quantity', 'ticket_ingested_at', 'finance_group_tag_id',
       'tag_name', 'access_area_name', 'usage_type_name'],
      dtype='object')

In [37]:
df=df.dropna(subset= ['ticket_id','validate_result','ticket_ticket_status','ticket_validate_date_time','ticket_group_quantity','ticket_ingested_at'])

In [38]:
df.head()

,ticket_id,validate_result,usage_group_quantity,usage_ingested_at,access_area_account_id,product_id,ticket_ticket_status,ticket_validate_date_time,ticket_group_quantity,ticket_ingested_at,finance_group_tag_id,tag_name,access_area_name,usage_type_name
8,a065625a-d8c8-c6b4-786b-019aa5648757,1,1,2026-01-01 16:54:52.806999+00:00,d368ba4c-9681-7fa9-4a6d-0198e56a8692,01476b48-641d-e487-553c-019a9c245d05,110,2025-11-21 07:50:00,1,2026-01-01 16:54:12.507372+00:00,ce7570a8-9d03-22da-7cd5-019a7db346aa,GA SDT,Six Flags General Admission,Entry
9,c54dfffe-17fc-27fe-24a6-019ac40cc028,1,1,2026-01-01 16:54:52.806999+00:00,d368ba4c-9681-7fa9-4a6d-0198e56a8692,01476b48-641d-e487-553c-019a9c245d05,109,2025-11-27 06:42:00,1,2026-01-01 16:54:24.937928+00:00,ce7570a8-9d03-22da-7cd5-019a7db346aa,GA SDT,Six Flags General Admission,Entry
10,31e7c587-7524-af8c-6c09-019a2b014733,1,1,2026-01-01 16:54:52.806999+00:00,d368ba4c-9681-7fa9-4a6d-0198e56a8692,033f20cb-4257-6742-22fa-01995152883e,110,2025-10-28 13:28:00,1,2026-01-01 16:53:53.692754+00:00,None,None,Six Flags General Admission,Entry
11,6496f778-6b85-72b4-3864-019905fae81d,1,1,2026-01-01 16:54:52.806999+00:00,d368ba4c-9681-7fa9-4a6d-0198e56a8692,045abe77-8052-f907-3836-0198f0317b36,110,2025-09-01 15:53:00,1,2026-01-01 16:53:42.330804+00:00,None,None,Six Flags General Admission,Entry
12,cc097bbc-b2bf-b4a0-74c6-01990a4ed1b7,1,1,2026-01-01 16:54:52.806999+00:00,d368ba4c-9681-7fa9-4a6d-0198e56a8692,045abe77-8052-f907-3836-0198f0317b36,110,2025-09-02 12:03:00,1,2026-01-01 16:53:42.330804+00:00,None,None,Six Flags General Admission,Entry

In [39]:
df=df.sort_values("usage_ingested_at",ascending=False)

In [40]:
df.head()

,ticket_id,validate_result,usage_group_quantity,usage_ingested_at,access_area_account_id,product_id,ticket_ticket_status,ticket_validate_date_time,ticket_group_quantity,ticket_ingested_at,finance_group_tag_id,tag_name,access_area_name,usage_type_name
23263,279edf29-c371-9adf-14c3-019ca48690d8,1,1,2026-02-28 15:31:07.232486+00:00,d368ba4c-9681-7fa9-4a6d-0198e56a8692,95c68ac9-ee7e-57ec-4b73-0198efa73a3d,0,2026-02-28 13:53:00,1,2026-02-28 14:30:54.313937+00:00,None,None,Six Flags General Admission,Entry
23262,974787d6-0158-08df-6ac5-019ca462330d,1,1,2026-02-28 14:31:04.559287+00:00,d368ba4c-9681-7fa9-4a6d-0198e56a8692,95c68ac9-ee7e-57ec-4b73-0198efa73a3d,0,2026-02-28 13:14:00,1,2026-02-28 14:30:54.313937+00:00,None,None,Six Flags General Admission,Entry
14552,d5d8020a-40a5-d223-054d-019ca3978a63,1,1,2026-02-28 10:31:01.466685+00:00,6dd8155c-e847-8250-475e-0198e568646b,2f5aabfd-acbd-2c87-6a5d-019ca38ccefc,0,2026-02-28 09:31:00,1,2026-02-28 10:30:52.650734+00:00,619dc61b-5300-b8d2-1239-019b88cded6c,Corporate,Six Flags Admission Dated,Entry
23454,b57835e3-72ec-bfaf-61e4-019c9f3a49a8,1,1,2026-02-27 14:31:05.084410+00:00,6dd8155c-e847-8250-475e-0198e568646b,b45c8559-93a1-37ad-4b30-019c4d6c0000,0,2026-02-27 13:12:00,1,2026-02-27 14:30:54.984081+00:00,c894fb0a-7fc2-3f0c-447c-019c0f13995b,Education,Six Flags Admission Dated,Entry
23586,786bc5b1-b56f-c473-37bc-019c9e986471,1,1,2026-02-27 11:31:06.780508+00:00,6dd8155c-e847-8250-475e-0198e568646b,d036583d-9679-0242-0995-019ac022db0e,0,2026-02-27 10:15:00,1,2026-02-27 11:30:56.393397+00:00,11583756-e1c3-d463-6754-0199e2f6b1bb,Admission,Six Flags Admission Dated,Entry

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23851 entries, 23263 to 23867
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ticket_id                  23851 non-null  object
 1   validate_result            23851 non-null  Int64
 2   usage_group_quantity       23851 non-null  Int64
 3   usage_ingested_at          23851 non-null  datetime64[us, UTC]
 4   access_area_account_id     23851 non-null  object
 5   product_id                 23851 non-null  object
 6   ticket_ticket_status       23851 non-null  Int64
 7   ticket_validate_date_time  23851 non-null  datetime64[us]
 8   ticket_group_quantity      23851 non-null  Int64
 9   ticket_ingested_at         23851 non-null  datetime64[us, UTC]
 10  finance_group_tag_id       222 non-null    object
 11  tag_name                   222 non-null    object
 12  access_area_name           23851 non-null  object
 13  usage_type_name            23851 non-null  object
dtypes: Int64(4), datetime64[us, UTC](2), datetime64[us](1), object(7)
memory usage: 2.8+ MB

In [23]:
df.columns

Index(['ticket_id', 'validate_result', 'usage_group_quantity',
       'usage_ingested_at', 'access_area_account_id', 'product_id',
       'ticket_ticket_status', 'ticket_validate_date_time',
       'ticket_group_quantity', 'ticket_ingested_at', 'finance_group_tag_id',
       'tag_name', 'access_area_name', 'usage_type_name'],
      dtype='object')

In [41]:
# df=df.dropna(subset= ['tag_name'])

In [45]:
df["validate_result"].value_counts()

validate_result
1     998
13      2
Name: count, dtype: Int64

In [46]:
df = df.drop(["validate_result","usage_group_quantity","ticket_group_quantity"],axis=1)

In [43]:
df=df.sample(1000)

In [49]:
df=df.drop(["usage_ingested_at","finance_group_tag_id","access_area_account_id"],axis=1)

In [50]:
df.head()

,ticket_id,product_id,ticket_ticket_status,ticket_validate_date_time,ticket_ingested_at,tag_name,access_area_name,usage_type_name
9952,17b26303-33ef-d7d7-7432-019ab5b50e88,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-24 11:52:00,2026-01-01 16:54:12.507372+00:00,None,Six Flags Admission Dated,Entry
166,5aaf3606-1121-404d-3b7f-019a79387a6a,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-12 17:59:00,2026-01-01 16:53:53.692754+00:00,None,Six Flags Admission Dated,Entry
8221,af2dfaef-0ca5-a852-6c5b-019aa73020e8,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-21 16:12:00,2026-01-01 16:54:12.507372+00:00,None,Six Flags Admission Dated,Entry
9554,811712ce-8858-afb8-503d-019ab20929ed,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-23 18:46:00,2026-01-01 16:54:12.507372+00:00,None,Six Flags Admission Dated,Entry
2289,aaacf4f7-d807-816f-4d5b-019a9d253976,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-19 17:24:00,2026-01-01 16:54:12.507372+00:00,None,Six Flags Admission Dated,Entry

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 9952 to 12302
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ticket_id                  1000 non-null   object
 1   product_id                 1000 non-null   object
 2   ticket_ticket_status       1000 non-null   Int64
 3   ticket_validate_date_time  1000 non-null   datetime64[us]
 4   ticket_ingested_at         1000 non-null   datetime64[us, UTC]
 5   tag_name                   10 non-null     object
 6   access_area_name           1000 non-null   object
 7   usage_type_name            1000 non-null   object
dtypes: Int64(1), datetime64[us, UTC](1), datetime64[us](1), object(5)
memory usage: 71.3+ KB

In [53]:
df["ticket_ticket_status"].value_counts()

ticket_ticket_status
110    854
0      143
109      2
105      1
Name: count, dtype: Int64

In [54]:
# Ensure correct datetime handling
df["ticket_validate_date_time"] = df["ticket_validate_date_time"].dt.tz_localize(None)

df["ticket_ingested_at"] = df["ticket_ingested_at"].dt.tz_convert("UTC")

In [55]:
df.head()

,ticket_id,product_id,ticket_ticket_status,ticket_validate_date_time,ticket_ingested_at,tag_name,access_area_name,usage_type_name
9952,17b26303-33ef-d7d7-7432-019ab5b50e88,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-24 11:52:00,2026-01-01 16:54:12.507372+00:00,None,Six Flags Admission Dated,Entry
166,5aaf3606-1121-404d-3b7f-019a79387a6a,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-12 17:59:00,2026-01-01 16:53:53.692754+00:00,None,Six Flags Admission Dated,Entry
8221,af2dfaef-0ca5-a852-6c5b-019aa73020e8,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-21 16:12:00,2026-01-01 16:54:12.507372+00:00,None,Six Flags Admission Dated,Entry
9554,811712ce-8858-afb8-503d-019ab20929ed,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-23 18:46:00,2026-01-01 16:54:12.507372+00:00,None,Six Flags Admission Dated,Entry
2289,aaacf4f7-d807-816f-4d5b-019a9d253976,0c35f2d2-a985-1c29-3bee-019a52a0e394,110,2025-11-19 17:24:00,2026-01-01 16:54:12.507372+00:00,None,Six Flags Admission Dated,Entry

In [57]:
df.tag_name.unique()

array([None, 'Tour & Travel', 'GA SDT', 'Admission', 'Corporate',
       'Government'], dtype=object)

In [59]:
df.columns = ['ticket_id', 'product_id', 'ticket_status',
       'ticket_validate_date_time', 'ticket_ingested_at', 'tag_name',
       'access_area_name', 'usage_type_name']

In [60]:
schema = [
    bigquery.SchemaField(
        "ticket_id",
        "STRING",
        mode="REQUIRED",
        description="Globally unique identifier of the admission ticket used for park entry validation."
    ),
    bigquery.SchemaField(
        "product_id",
        "STRING",
        mode="REQUIRED",
        description="Identifier of the ticket product associated with the admission (e.g., ticket type or package SKU)."
    ),
    bigquery.SchemaField(
        "ticket_status",
        "INT64",
        mode="REQUIRED",
        description="Commercial classification or sales segment assigned to the ticket (e.g., Tour & Travel, Corporate, Government, GA SDT, Admission). Used for revenue segmentation and reporting."
    ),
    bigquery.SchemaField(
        "ticket_validate_date_time",
        "DATETIME",
        mode="REQUIRED",
        description="Date and time when the ticket was validated at the park access control point."
    ),
    bigquery.SchemaField(
        "ticket_ingested_at",
        "TIMESTAMP",
        mode="REQUIRED",
        description="System timestamp indicating when the ticket validation record was ingested into the data platform."
    ),
    bigquery.SchemaField(
        "tag_name",
        "STRING",
        mode="NULLABLE",
        description="Optional operational or promotional tag assigned to the ticket (may be null if no tag applied)."
    ),
    bigquery.SchemaField(
        "access_area_name",
        "STRING",
        mode="REQUIRED",
        description="Name of the park access area or gate where the ticket was validated (e.g., Six Flags Admission Dated)."
    ),
    bigquery.SchemaField(
        "usage_type_name",
        "STRING",
        mode="REQUIRED",
        description="Classification of ticket usage event (e.g., Entry, Re-entry, Upgrade)."
    ),
]

In [61]:
project_id = "prj-ai-dev-qic"
dataset_id = "qic_vgs"
table_id = f"{project_id}.{dataset_id}.l1_admission"

client = bigquery.Client(project=project_id)

job_config = bigquery.LoadJobConfig(
    schema=schema,
    write_disposition="WRITE_TRUNCATE"
)

load_job = client.load_table_from_dataframe(
    df,
    table_id,
    job_config=job_config
)

load_job.result()

print("Table created successfully with schema + descriptions.")

Table created successfully with schema + descriptions.

In [30]:
dataset = bigquery.Dataset("prj-ai-dev-qic.qic_vgs")

dataset.location = "eu"

try:
    # exists_ok=True prevents errors if the dataset is already there
    dataset = bq_client.create_dataset(dataset, exists_ok=True)
    print(f"✅ Dataset ready: {str(dataset)}")
except Exception as e:
    print(f"❌ Error creating dataset {str(dataset)}: {e}")

✅ Dataset ready: Dataset(DatasetReference('prj-ai-dev-qic', 'qic_vgs'))

In [6]:
sql =f"SELECT * FROM `prj-qc-dev-qic.ds_dev_qic_gold_qbrain.l1_ticket_sales`"
df = bq_client.query_and_wait(sql).to_dataframe(create_bqstorage_client=False)

In [7]:
df.shape

(216222, 59)

In [ ]:
df.head()

In [8]:
df.columns

Index(['date', 'time', 'sale_item_id', 'transaction_id', 'sale_code_pnr',
       'client_id', 'client_code', 'client_username', 'client_username_email',
       'client_name', 'client_category', 'sale_channel_code',
       'sale_channel_name', 'order_location_code', 'order_location_name',
       'order_operating_area_code', 'order_operating_area_name',
       'order_workstation_code', 'order_workstation_name',
       'order_account_username', 'order_account_username_email',
       'order_user_account_name', 'transaction_location_code',
       'transaction_location_name', 'transaction_operating_area_code',
       'transaction_operating_area_name', 'transaction_workstation_code',
       'transaction_workstation_name', 'transaction_account_username',
       'transaction_account_username_email', 'transaction_user_account_name',
       'transaction_serial', 'transaction_type_code', 'approved', 'paid',
       'encoded', 'printed', 'validated', 'product_code', 'product_name',
       'deposit_account_id', 'deposit_account_code', 'deposit_account_name',
       'quantity', 'unit_tax', 'unit_amount', 'unit_attribute_amount',
       'total_tax', 'total_amount', 'paid_amount', 'paid_tax', 'print_group',
       'finance_group', 'admission_group', 'area_group', 'attribute_items',
       'tags', 'payments', 'entity_change_id'],
      dtype='object')

In [68]:
df = df[[
    "date",
    "time",
    "transaction_id",
    "transaction_type_code",
    "product_code",
    "product_name",
    "admission_group",
    "client_category",
    "sale_channel_name",
    "transaction_location_name",
    "quantity",
    "total_amount",
    "total_tax",
    "paid_amount",
    "approved",
    "paid"
]]

In [75]:
df["client_category"].value_counts()

client_category
Reservation Owner         878
Person                     13
Tour & Trade                5
Energy                      3
Premier Partner             2
Aviation and Logistics      2
Private Schools             1
Entertainment & Events      1
Public Schools              1
Corporate                   1
Name: count, dtype: int64

In [70]:
df=df.sample(1000)

In [71]:
df.head()

,date,time,transaction_id,transaction_type_code,product_code,product_name,admission_group,client_category,sale_channel_name,transaction_location_name,quantity,total_amount,total_tax,paid_amount,approved,paid
130786,02/12/2025,19:47,f4d160ec-5db6-46ea-3eca-019ae09accb3,1,SF_SDT_ADT,Six Flags Single Day Ticket Standard,Adult,Reservation Owner,eCommerce,Six Flags,2,895.000000000,116.740000000,895.000000000,True,True
71477,07/11/2025,14:25,40260c9f-9d88-418b-5734-019a5eb51f49,1,SF_SDT_ADT,Six Flags Single Day Ticket Standard,Adult,Reservation Owner,eCommerce,Six Flags,1,446.790000000,58.280000000,695.000000000,True,True
98747,25/12/2025,15:10,0b3f52e5-fdd5-15e8-3c0b-019b560f8516,1,SF_CMBSDT_GA,Family Fun Bundle,Gen Admission,Reservation Owner,eCommerce,Six Flags,1,0E-9,156.500000000,1200.000000000,True,True
162308,01/01/2026,11:35,1c7fcbb8-d316-6591-17da-019b7957a0c8,1,SF_CMBSDT_GST,Family Bundle Guest,Adult,Reservation Owner,eCommerce,Six Flags,5,1200.000000000,0E-9,1200.000000000,True,True
21277,02/12/2025,19:43,95b3063b-9191-5c68-4bfa-019ae097d59e,1,SF_SDT_ADT,Six Flags Single Day Ticket Standard,Adult,Reservation Owner,eCommerce,Six Flags,1,320.000000000,41.740000000,320.000000000,True,True

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 130786 to 82318
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   date                       1000 non-null   object
 1   time                       1000 non-null   object
 2   transaction_id             1000 non-null   object
 3   transaction_type_code      1000 non-null   Int64
 4   product_code               932 non-null    object
 5   product_name               932 non-null    object
 6   admission_group            652 non-null    object
 7   client_category            907 non-null    object
 8   sale_channel_name          799 non-null    object
 9   transaction_location_name  1000 non-null   object
 10  quantity                   932 non-null    Int64
 11  total_amount               932 non-null    object
 12  total_tax                  932 non-null    object
 13  paid_amount                1000 non-null   object
 14  approved                   1000 non-null   boolean
 15  paid                       1000 non-null   boolean
dtypes: Int64(2), boolean(2), object(12)
memory usage: 123.0+ KB

In [74]:
# Convert date and time
df["date"] = pd.to_datetime(
    df["date"],
    format="%d/%m/%Y",
    errors="coerce"
).dt.date
df["time"] = pd.to_datetime(df["time"], errors="coerce").dt.time

# Convert numeric fields
df["total_amount"] = pd.to_numeric(df["total_amount"], errors="coerce")
df["total_tax"] = pd.to_numeric(df["total_tax"], errors="coerce")
df["paid_amount"] = pd.to_numeric(df["paid_amount"], errors="coerce")

/var/tmp/ipykernel_519859/2495962280.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["time"] = pd.to_datetime(df["time"], errors="coerce").dt.time

In [76]:
from google.cloud import bigquery

schema = [

    bigquery.SchemaField(
        "date",
        "DATE",
        mode="REQUIRED",
        description="Transaction business date when the sale occurred."
    ),

    bigquery.SchemaField(
        "time",
        "TIME",
        mode="NULLABLE",
        description="Transaction time of the sale event."
    ),

    bigquery.SchemaField(
        "transaction_id",
        "STRING",
        mode="REQUIRED",
        description="Unique identifier of the sales transaction."
    ),

    bigquery.SchemaField(
        "transaction_type_code",
        "INT64",
        mode="REQUIRED",
        description="Operational transaction type code indicating sale, refund, or adjustment."
    ),

    bigquery.SchemaField(
        "product_code",
        "STRING",
        mode="NULLABLE",
        description="Unique product identifier for the sold item."
    ),

    bigquery.SchemaField(
        "product_name",
        "STRING",
        mode="NULLABLE",
        description="Name of the ticket product sold in the transaction."
    ),

    bigquery.SchemaField(
        "admission_group",
        "STRING",
        mode="NULLABLE",
        description="Product grouping classification indicating admission type such as Child, Adult, Family etc"
    ),

    bigquery.SchemaField(
        "client_category",
        "STRING",
        mode="NULLABLE",
        description="Customer segment classification (e.g., Corporate, Government, General Admission)."
    ),

    bigquery.SchemaField(
        "sale_channel_name",
        "STRING",
        mode="NULLABLE",
        description="Sales channel through which the transaction was processed (e.g., Online, POS, Travel Partner)."
    ),

    bigquery.SchemaField(
        "transaction_location_name",
        "STRING",
        mode="REQUIRED",
        description="Location where the transaction was executed."
    ),

    bigquery.SchemaField(
        "quantity",
        "INT64",
        mode="NULLABLE",
        description="Number of units sold for the product within the transaction."
    ),

    bigquery.SchemaField(
        "total_amount",
        "FLOAT",
        mode="NULLABLE",
        description="Total gross amount for the line item before or including tax depending on system configuration."
    ),

    bigquery.SchemaField(
        "total_tax",
        "FLOAT",
        mode="NULLABLE",
        description="Total tax amount applied to the transaction line item."
    ),

    bigquery.SchemaField(
        "paid_amount",
        "FLOAT",
        mode="REQUIRED",
        description="Amount paid for the transaction line item."
    ),

    bigquery.SchemaField(
        "approved",
        "BOOL",
        mode="REQUIRED",
        description="Indicates whether the transaction was approved."
    ),

    bigquery.SchemaField(
        "paid",
        "BOOL",
        mode="REQUIRED",
        description="Indicates whether payment was successfully completed."
    ),
]

In [77]:
project_id = "prj-ai-dev-qic"
dataset_id = "qic_vgs"
table_id = f"{project_id}.{dataset_id}.l1_ticket_sales"

client = bigquery.Client(project=project_id)

job_config = bigquery.LoadJobConfig(
    schema=schema,
    write_disposition="WRITE_TRUNCATE"
)

load_job = client.load_table_from_dataframe(
    df,
    table_id,
    job_config=job_config
)

load_job.result()

print("l1_ticket_sales created successfully.")

l1_ticket_sales created successfully.

In [64]:
dataset = bigquery.Dataset("prj-ai-dev-qic.qic_risk")

dataset.location = "eu"

try:
    # exists_ok=True prevents errors if the dataset is already there
    dataset = bq_client.create_dataset(dataset, exists_ok=True)
    print(f"✅ Dataset ready: {str(dataset)}")
except Exception as e:
    print(f"❌ Error creating dataset {str(dataset)}: {e}")

✅ Dataset ready: Dataset(DatasetReference('prj-ai-dev-qic', 'qic_risk'))

In [21]:
sql =f"SELECT * FROM `prj-qc-dev-qic.ds_dev_qic_gold_risk.l1_risk_data_extract`"
df = bq_client.query_and_wait(sql).to_dataframe(create_bqstorage_client=False)

In [22]:
df.head()

,Item ID,Record Type,L2 Label,District,District BU''s,Sub-District,Portfolio,Project,Sub-Project,Parent Name,Project Name,BU Attributes,Project Status,Risk ID,Date Raised,Last Review,Risk Title,Risk Description,Cause,Effect,Approval Date,Risk Status,Closed Date,Risk Owner,Progress Stage,RIBA Phase,Scoring Scheme,Current Rationale,Current Probability Band,Current Probability,Current Driving Band,Target Rationale,Target Probability Band,Target Probability,Target Driving Band,Current Risk Score,Current Risk Level,Target Risk Score,Target Risk Level,Current EMV,Target EMV,Current ETV,Target ETV,Exposure,Driver,Stage,Category 1,Current Band,Distribution,Min,Exp,Max,Target Band,Distribution_1,Min_2,Exp_3,Max_4,Category 2,Current Band_5,Distribution_6,Min_7,Exp_8,Max_9,Target Band_10,Distribution_11,Min_12,Exp_13,Max_14,Category 3,Category 3 rating,Current Band_15,Target Band_16,Category 4,Category 4 rating,Current Band_17,Target Band_18,RBS,Exposure Start,Exposure End,impactkey,escalation,riskLastUpdated,Current Probability Band Desc,CURRENT impact band,tar_Distribution
0,49,Risk,01. Qiddiya City by Districts,District 12 - Resort Core,D12 Entertainment Business Unit,Sub-District 1 - East,Six Flags Qiddiya,Six Flags Qiddiya,<NA>,Six Flags Qiddiya,Six Flags Qiddiya,Business Unit > Entertainment,Live,3.000000000,2021-09-06,2023-07-26,Ride Vendor delivery and Procurement timing no...,Prolonged release of rides engineering and mai...,1. Prolonged process of finalization of rides ...,1. Extended duration required to obtain Rides ...,2021-09-06,Closed - Mitigated,2024-07-07,"Courtney, David",2. Asset Delivery,AA 1. Corporate Risk,QDC Project Budget SAR 5Bn,DMSIC contracts are still in progress for appr...,1,5.000000000,1,None,1,5.000000000,1,1.000000000,Negligible,1.000000000,Negligible,625000.000000000,625000.000000000,1.000000000,1.000000000,Threat,Time,AA 1. Corporate Risk,Cost,Negligible,Single Point,12500000.0,12500000.0,12500000.0,Negligible,Single Point,72000.0,72000.0,72000.0,Time,Negligible,Single Point,0.0,0.0,0.0,Negligible,Single Point,0.0,0.0,0.0,Reputation,0,NIL,NIL,Legal and Regulatory,0,NIL,NIL,Development and Delivery,2019-04-18,NaT,3,Undefined,2024-07-07,Rare,Negligible,Single Point
1,49,Risk,01. Qiddiya City by Districts,District 12 - Resort Core,D12 Entertainment Business Unit,Sub-District 1 - East,Six Flags Qiddiya,Six Flags Qiddiya,<NA>,Six Flags Qiddiya,Six Flags Qiddiya,Business Unit > Entertainment,Live,16.000000000,2021-09-06,NaT,Operational Security,"Overall security strategy, procedures and proc...","1. Operational Security Report, S18143-0100D-R...",1. Potential for security incident during oper...,2021-09-06,Closed - Mitigated,2023-09-19,"Courtney, David",2. Asset Delivery,AD 7. Completion,QDC Project Budget SAR 5Bn,This cannot occur until operations commence bu...,1,5.000000000,1,None,1,5.000000000,1,1.000000000,Negligible,1.000000000,Negligible,625000.000000000,625000.000000000,0E-9,0E-9,Threat,Cost (SAR),AD 7. Completion,Cost,Negligible,Single Point,12500000.0,12500000.0,12500000.0,Negligible,Single Point,0.0,0.0,0.0,Time,NIL,Single Point,0.0,0.0,0.0,NIL,Single Point,0.0,0.0,0.0,Reputation,0,NIL,NIL,Legal and Regulatory,0,NIL,NIL,Development and Delivery,2019-09-01,2023-09-30,16,Undefined,2023-09-19,Rare,Negligible,Single Point
2,49,Risk,01. Qiddiya City by Districts,District 12 - Resort Core,D12 Entertainment Business Unit,Sub-District 1 - East,Six Flags Qiddiya,Six Flags Qiddiya,<NA>,Six Flags Qiddiya,Six Flags Qiddiya,Business Unit > Entertainment,Live,1492.000000000,2023-06-08,2024-10-30,Estimated FX Currency potential gain in DMSIC ...,Estimated FX Currency potential gain in DMSIC ...,Currency Fluctuation,Budget positive impact. Changes in the exchang...,2023-06-08,Closed - Expired,2025-02-19,"Farrel, Adam",2. Asset Delivery,AD 6. Construction Commencement,QDC Project Budget SAR 5Bn,Keep the the FX exchange in record and update ...,-3,50.000000000,-1,None,-4,77.500000000,-2,-3.000000000,Very Low Opp,-8.000000000,Low Opp,-6250000.000000000,-29062500.000000000,0E-9,0E-9,Opportunity,Cost (SAR),AD 6. Construction Commencement,Cost,Negligible,Beta Pert,-12500000.0,-12500000.0,-12500000.0,Minor,Beta Pert,0.0,0.0,0.0,Time,NIL,Beta Pert,NaN,NaN,NaN,NIL,Beta Pert,NaN,NaN,NaN,None,<NA>,None,None,None,<NA>,None,None,Financial / Reporting,2022-12-01,NaT,1539,Undefined,2025-02-19,Possible,Negligible,Beta Pert
3,49,Risk,01. Qiddiya City by Districts,District 12 - Resort Core,D12 Entertainment Business Unit,Sub-District 1 - East,Six Flags Qiddiya,Six Flags Qiddiya,<NA>,Six Flags Qiddiya,Six Flags Qiddiya,Business Unit > Entertainment,Live,341.000000000,2022-02-03,NaT,Water Supply - Temporary,There is an opportunity to install pipe networ...,We have water wells already drilled that will ...,1. Utilization of water from wells is potentia...,2022-02-03,Closed - Rejected,2023-12-11,"McCann, Michael",2. Asset Delivery,AD 6. Construction Commencement,QDC Project Budget SAR 5Bn,This is possible but needs a number of parties...,-3,50.000000000,-1,None,-3,50.000000000,-1,-3.000000000,Very Low Opp,-3.000000000,Very Low Opp,-25.000000000,-35.000000000,0E-9,0E-9,Opportunity,Cost (SAR),AD 6. Construction Commencement,Cost,Negligible,Single Point,-50.0,-50.0,-50.0,Negligible,Single Point,0.0,0.0,0.0,Time,NIL,Single Point,0.0,0.0,0.0,NIL,Single Point,0.0,0.0,0.0,Reputation,0,NIL,NIL,Legal and Regulatory,0,NIL,NIL,Development and Delivery,2023-12-11,NaT,379,Undefined,2023-12-11,Possible,Negligible,Single Point
4,50,Risk,01. Qiddiya City by Districts,District 12 - Resort Core,D12 Entertainment Business Unit,Sub-District 1 - East,Aquarabia,Water Theme Park,<NA>,Aquarabia,Water Theme Park,Business Unit > Entertainment,Live,3145.000000000,2024-05-09,NaT,Reduction in final forecasted cost (Opportunity),There is an opportunity that continuing strong...,"Due to design changes, RFI's and Qiddiya Instr...",Potential saving on final forecasted cost,2024-05-09,Open,NaT,"O'Donovan, Tadgh",2. Asset Delivery,AD 7. Completion,QDC Project Budget SAR 3Bn,The probability is possible and the impact is ...,-3,50.000000000,-1,Continued the strong negotiations with ESA bri...,-4,77.500000000,-1,-3.000000000,Very Low Opp,-4.000000000,Very Low Opp,-500000.000000000,-775000.000000000,0E-9,0E-9,Opportunity,Cost (SAR),AD 7. Completion,Cost,Negligible,Single Point,-1000000.0,-1000000.0,-1000000.0,Negligible,Single Point,0.0,0.0,0.0,Time,NIL,Single Point,NaN,NaN,NaN,NIL,Single Point,NaN,NaN,NaN,None,<NA>,None,None,None,<NA>,None,None,L2.3.13 Budget Management-> Development and De...,2024-05-09,NaT,3194,0. No Escalation Required,2026-02-24,Possible,Negligible,Single Point

In [6]:
df.columns

Index(['Item ID', 'Record Type', 'L2 Label', 'District', 'District BU''s',
       'Sub-District', 'Portfolio', 'Project', 'Sub-Project', 'Parent Name',
       'Project Name', 'BU Attributes', 'Project Status', 'Risk ID',
       'Date Raised', 'Last Review', 'Risk Title', 'Risk Description', 'Cause',
       'Effect', 'Approval Date', 'Risk Status', 'Closed Date', 'Risk Owner',
       'Progress Stage', 'RIBA Phase', 'Scoring Scheme', 'Current Rationale',
       'Current Probability Band', 'Current Probability',
       'Current Driving Band', 'Target Rationale', 'Target Probability Band',
       'Target Probability', 'Target Driving Band', 'Current Risk Score',
       'Current Risk Level', 'Target Risk Score', 'Target Risk Level',
       'Current EMV', 'Target EMV', 'Current ETV', 'Target ETV', 'Exposure',
       'Driver', 'Stage', 'Category 1', 'Current Band', 'Distribution', 'Min',
       'Exp', 'Max', 'Target Band', 'Distribution_1', 'Min_2', 'Exp_3',
       'Max_4', 'Category 2', 'Current Band_5', 'Distribution_6', 'Min_7',
       'Exp_8', 'Max_9', 'Target Band_10', 'Distribution_11', 'Min_12',
       'Exp_13', 'Max_14', 'Category 3', 'Category 3 rating',
       'Current Band_15', 'Target Band_16', 'Category 4', 'Category 4 rating',
       'Current Band_17', 'Target Band_18', 'RBS', 'Exposure Start',
       'Exposure End', 'impactkey', 'escalation', 'riskLastUpdated',
       'Current Probability Band Desc', 'CURRENT impact band',
       'tar_Distribution'],
      dtype='object')

In [23]:
df=df[ [
    "Record Type",
    "District",
    "Sub-District",
    "Portfolio",
    "Project",
    "Sub-Project",
    "Project Name",
    "BU Attributes",
    "Project Status",
    "Risk ID",
    "Date Raised",
    "Last Review",
    "Risk Title",
    "Risk Description",
    "Cause",
    "Effect",
    "Approval Date",
    "Risk Status",
    "Closed Date",
    "Risk Owner",
    "Progress Stage",
    "RIBA Phase",
    "Current Rationale",
    "Current Probability",
    "Target Rationale",
    "Target Probability",
    "Current Risk Score",
    "Current Risk Level",
    "Target Risk Score",
    "Target Risk Level",
    "Current EMV",
    "Target EMV",
    "Current ETV",
    "Target ETV",
    "Exposure",
    "Driver",
    "Stage",
    "Category 1",
    "Current Band",
    "Category 2",
    "Category 3",
    "Category 4",
    "RBS",
    "Exposure Start",
    "Exposure End",
    "escalation"
]]

In [24]:
df=df.sample(1000)

In [25]:
risk = df.copy()

In [51]:
sql =f"SELECT * FROM `prj-qc-dev-qic.ds_dev_qic_gold_risk.l1_response_data_extract`"
df = bq_client.query_and_wait(sql).to_dataframe(create_bqstorage_client=False)

In [52]:
df =df[ [
    "Project Name",
    "Plan ID",
    "High level Description",
    "Response ID",
    "Response Owner",
    "title",
    "status",
    "description",
    "Start Date",
    "Due Date",
    "Days from Due",
    "Response Due",
    "Completed_Closed",
    "Last updated",
    "Planned Cost",
    "Actual Cost",
    "Percent Complete",
    "Related Risk ID"
]]

In [53]:
df.columns = [ 'Plan ID', 'High level Description', 'Response ID',
       'Response Owner', 'title', 'status', 'description', 'Start Date',
       'Due Date', 'Days from Due', 'Response Due', 'Completed_Closed',
       'Last updated', 'Planned Cost', 'Actual Cost', 'Percent Complete',
       'Risk ID']

In [54]:
final_risk = risk.merge(df, on = ["Risk ID"],how="left")

In [60]:
final_risk.head(2).to_json()

'{"Record Type":{"0":"Risk","1":"Risk"},"District":{"0":"District 12 - Resort Core","1":"District 12 - Resort Core"},"Sub-District":{"0":"Sub-District 4 - Southwest","1":"Sub-District 4 - Southwest"},"Portfolio":{"0":null,"1":null},"Project":{"0":null,"1":null},"Sub-Project":{"0":null,"1":null},"Project Name_x":{"0":"Sub-District 4 - Southwest","1":"Sub-District 4 - Southwest"},"BU Attributes":{"0":"Business Unit > Entertainment","1":"Business Unit > Entertainment"},"Project Status":{"0":"Live","1":"Live"},"Risk ID":{"0":9787.0,"1":9787.0},"Date Raised":{"0":1771200000000,"1":1771200000000},"Last Review":{"0":null,"1":null},"Risk Title":{"0":"Helicopter Flight OLS Path and Planned Tower Cranes at Janadriya Project","1":"Helicopter Flight OLS Path and Planned Tower Cranes at Janadriya Project"},"Risk Description":{"0":"The proposed tower crane locations may conflict with the helipad\\u2019s helicopter flight envelope.","1":"The proposed tower crane locations may conflict with the helipad\\u2019s helicopter flight envelope."},"Cause":{"0":"Height and reach of the tall crane booms near the Helipad","1":"Height and reach of the tall crane booms near the Helipad"},"Effect":{"0":"potentially infringing the Obstacle Limitation Surface (OLS) and affecting safe flight operations","1":"potentially infringing the Obstacle Limitation Surface (OLS) and affecting safe flight operations"},"Approval Date":{"0":1771200000000,"1":1771200000000},"Risk Status":{"0":"Open","1":"Open"},"Closed Date":{"0":null,"1":null},"Risk Owner":{"0":"Boylan, Jasper","1":"Boylan, Jasper"},"Progress Stage":{"0":"Undefined","1":"Undefined"},"RIBA Phase":{"0":"LS 4. Construction Commencement","1":"LS 4. Construction Commencement"},"Current Rationale":{"0":"","1":""},"Current Probability":{"0":77.5,"1":77.5},"Target Rationale":{"0":"Avoid Helicopter Flight Disruption","1":"Avoid Helicopter Flight Disruption"},"Target Probability":{"0":50.0,"1":50.0},"Current Risk Score":{"0":12.0,"1":12.0},"Current Risk Level":{"0":"Moderate","1":"Moderate"},"Target Risk Score":{"0":3.0,"1":3.0},"Target Risk Level":{"0":"Very Low","1":"Very Low"},"Current EMV":{"0":0.0,"1":0.0},"Target EMV":{"0":0.0,"1":0.0},"Current ETV":{"0":null,"1":null},"Target ETV":{"0":null,"1":null},"Exposure":{"0":"Threat","1":"Threat"},"Driver":{"0":"Health and Safety ()","1":"Health and Safety ()"},"Stage":{"0":"LS 4. Construction Commencement","1":"LS 4. Construction Commencement"},"Category 1":{"0":"Health and Safety","1":"Health and Safety"},"Current Band":{"0":"Moderate","1":"Moderate"},"Category 2":{"0":null,"1":null},"Category 3":{"0":null,"1":null},"Category 4":{"0":null,"1":null},"RBS":{"0":"ZZ Operational (Historic)-> ZZ Operational (Historic)","1":"ZZ Operational (Historic)-> ZZ Operational (Historic)"},"Exposure Start":{"0":1771200000000,"1":1771200000000},"Exposure End":{"0":null,"1":null},"escalation":{"0":"0. No Escalation Required","1":"0. No Escalation Required"},"Project Name_y":{"0":"Sub-District 4 - Southwest","1":"Sub-District 4 - Southwest"},"Plan ID":{"0":9683,"1":9683},"High level Description":{"0":"Mitigate the potential conflict between planned crane installations and the helipad\\u2019s helicopter flight path, construction teams should conduct an OLS compliance assessment, adjust crane heights or positions where necessary, and ensure all cranes are equipped with aviation lighting and active anti\\u2011collision systems. Non-operational booms must be lowered, and all crane activities should follow the formal Crane Operation Notification process, supported by daily coordination between crane coordinators and aviation stakeholders to maintain safe airspace conditions.","1":"Mitigate the potential conflict between planned crane installations and the helipad\\u2019s helicopter flight path, construction teams should conduct an OLS compliance assessment, adjust crane heights or positions where necessary, and ensure all cranes are equipped with aviation lighting and active anti\\u2011collision systems. Non-operational booms must be lowered, and all crane activities should follow the formal Crane Operation Notification process, supported by daily coordination between crane coordinators and aviation stakeholders to maintain safe airspace conditions."},"Response ID":{"0":"14560","1":"14561"},"Response Owner":{"0":"Boylan, Jasper","1":"Devlin, James"},"title":{"0":"Conduct an OLS compliance check and adjust crane height\\/position to avoid infringements and lower non-operational crane booms and ensure aviation lighting is installed and functioning.","1":"Submit Crane Operation Notification Forms and coordinate approvals with aviation stakeholders in addition to\\nholding coordination meetings between crane coordinators and heliport\\/aviation teams."},"status":{"0":"Action In Progress","1":"Action In Progress"},"description":{"0":"Conduct an OLS compliance check and adjust crane height\\/position to avoid infringements and lower non-operational crane booms and ensure aviation lighting is installed and functioning.","1":"Submit Crane Operation Notification Forms and coordinate approvals with aviation stakeholders in addition to holding coordination meetings between crane coordinators and heliport\\/aviation teams."},"Start Date":{"0":1771200000000,"1":1771200000000},"Due Date":{"0":1780185600000,"1":1780185600000},"Days from Due":{"0":90,"1":90},"Response Due":{"0":"Due 90","1":"Due 90"},"Completed_Closed":{"0":null,"1":null},"Last updated":{"0":1771200000000,"1":1771200000000},"Planned Cost":{"0":0.0,"1":0.0},"Actual Cost":{"0":null,"1":null},"Percent Complete":{"0":0.0,"1":0.0}}'

In [56]:
final_risk.shape

(1313, 63)

In [61]:
final_risk.columns

Index(['Record Type', 'District', 'Sub-District', 'Portfolio', 'Project',
       'Sub-Project', 'Project Name_x', 'BU Attributes', 'Project Status',
       'Risk ID', 'Date Raised', 'Last Review', 'Risk Title',
       'Risk Description', 'Cause', 'Effect', 'Approval Date', 'Risk Status',
       'Closed Date', 'Risk Owner', 'Progress Stage', 'RIBA Phase',
       'Current Rationale', 'Current Probability', 'Target Rationale',
       'Target Probability', 'Current Risk Score', 'Current Risk Level',
       'Target Risk Score', 'Target Risk Level', 'Current EMV', 'Target EMV',
       'Current ETV', 'Target ETV', 'Exposure', 'Driver', 'Stage',
       'Category 1', 'Current Band', 'Category 2', 'Category 3', 'Category 4',
       'RBS', 'Exposure Start', 'Exposure End', 'escalation', 'Project Name_y',
       'Plan ID', 'High level Description', 'Response ID', 'Response Owner',
       'title', 'status', 'description', 'Start Date', 'Due Date',
       'Days from Due', 'Response Due', 'Completed_Closed', 'Last updated',
       'Planned Cost', 'Actual Cost', 'Percent Complete'],
      dtype='object')

In [63]:
final_risk.head(50).to_excel("test.xlsx",index=False)

In [14]:
df = pd.read_excel("data/l1_risk_regenerated.xlsx")

In [15]:
df.head()

,Record Type,District,Sub-District,Portfolio,Project,Sub-Project,Project Name,BU Attributes,Project Status,Risk ID,Date Raised,Last Review,Risk Title,Risk Description,Cause,Effect,Approval Date,Risk Status,Closed Date,Risk Owner,Progress Stage,RIBA Phase,Current Rationale,Current Probability,Target Rationale,Target Probability,Current Risk Score,Current Risk Level,Target Risk Score,Target Risk Level,Current EMV,Target EMV,Current ETV,Target ETV,Exposure,Driver,Stage,Category 1,Current Band,Category 2,Category 3,Category 4,RBS,Exposure Start,Exposure End,escalation,Project Name1,Plan ID,High level Description,Response ID,Response Owner,title,status,description,Start Date,Due Date,Days from Due,Response Due,Completed_Closed,Last updated,Planned Cost,Actual Cost,Percent Complete,Related Risk ID,Risk Title.1,Risk Status.1
0,Risk,Entertainment District,Evansport,Entertainment,PRJ-2001,SUB-15,Retail Boulevard Development,Development,Delayed,RISK-1000,2026-03-01,2026-05-19,Delay in Authority Clearance,Regulatory approvals are not received within p...,Incomplete documentation submission and compli...,Construction start delay and milestone impact.,2026-03-16,Closed,2026-05-22,Michael Green,Handover,RIBA 3,Limited visibility on contractor performance m...,27,Authority approvals streamlined via early enga...,22,108,High,88,Critical,5012741.21,4084455.80,362,294,Minor,Time,Execution,Commercial,Band 2,Procurement,Authority,Commercial,RBS-452.9,2026-04-19,2026-09-16,Yes,Project 4,PLAN-6612,Implement proactive procurement strategy for l...,RESP-23179,Kelsey Murphy,Early Procurement Planning,Not Started,Identify long-lead materials during early desi...,2026-03-01,2026-05-09,68,2026-05-09,Yes,2026-03-02,1222389.90,1140782.69,93.32,RISK-1028,Related Risk Title 0,Closed
1,Risk,Sports District,South Paula,Sports,PRJ-2002,SUB-10,Retail Boulevard Development,Development,Completed,RISK-1001,2026-03-01,2026-05-12,Utility Connection Delay,Permanent power or water connections are delayed.,Coordination gaps with utility authorities.,Testing & commissioning activities postponed.,2026-03-23,Closed,2026-06-11,Matthew Ross,Execution,RIBA 2,Dependency on external stakeholders limits imm...,29,Risk exposure reduced to acceptable levels thr...,22,29,Moderate,22,High,6218505.43,4717486.88,265,201,Minor,Reputation,Design,Design,Band 3,Procurement,Procurement,Procurement,RBS-373.6,2026-04-26,2026-09-25,Yes,Project 17,PLAN-5035,Improve quality assurance controls.,RESP-26365,Kathleen Washington,QA/QC Enhancement Plan,Completed,"Deploy inspection test plans (ITPs), third-par...",2026-03-01,2026-05-12,71,2026-05-12,No,2026-03-02,1480665.23,942484.74,63.65,RISK-1059,Related Risk Title 1,Closed
2,Risk,Retail District,East Marytown,Retail,PRJ-2003,SUB-5,Stadium Main Structure Build,Delivery,Active,RISK-1002,2026-03-01,2026-05-09,Delay in Material Delivery,Critical construction materials are not delive...,Supplier production backlog and late procureme...,Schedule slippage impacting structural and fin...,2026-03-08,Closed,2026-05-23,Brian Garcia DDS,Execution,RIBA 3,Budget constraints are restricting full implem...,79,Quality and compliance risks controlled throug...,57,316,Critical,228,High,3704558.77,2672909.49,72,51,Minor,Time,Concept,Construction,Band 3,Procurement,Authority,Authority,RBS-444.8,2026-03-13,2026-04-25,Yes,Project 9,PLAN-6377,Enhance structured design approval workflow.,RESP-25287,Alicia Scott,Design Review Governance,In Progress,Implement formal design review cycles with def...,2026-03-01,2026-04-21,50,2026-04-21,Yes,2026-03-02,598802.81,313141.47,52.29,RISK-1036,Related Risk Title 2,Closed
3,Risk,Hospitality District,Edwardsborough,Hospitality,PRJ-2004,SUB-10,Retail Boulevard Development,Commercial,Active,RISK-1003,2026-03-01,2026-04-13,Design Coordination Conflict,Clashes identified between architectural and M...,Lack of BIM coordination prior to IFC issuance.,On-site rework and additional construction costs.,2026-03-25,Mitigating,NaT,Julie Bryant,Concept,RIBA 2,Risk impact remains moderate due to incomplete...,65,Residual risk maintained within approved risk ...,43,260,Low,172,Moderate,662171.63,438052.00,225,148,Threat,Quality,Concept,Design,Band 2,Design,Authority,Design,RBS-380.1,2026-04-27,2026-09-10,Yes,Project 6,PLAN-6503,Proactively coordinate with utility providers.,RESP-92997,Robyn Mccarthy,Utility Early Engagement,Not Started,Initiate early application submissions and tra...,2026-03-01,2026-04-18,47,2026-04-18,Yes,2026-03-02,484001.35,378701.63,78.24,RISK-1078,Related Risk Title 3,Mitigating
4,Risk,Hospitality District,North Sharonhaven,Hospitality,PRJ-2004,SUB-14,Retail Boulevard Development,Commercial,On Hold,RISK-1004,2026-03-01,2026-05-08,Delay in Design Approval,IFC drawings are pending approval beyond agree...,Multiple stakeholder review cycles and late co...,Contractor mobilization delay and rework risk.,2026-03-17,Open,NaT,Debra James,Design,RIBA 5,Limited visibility on contractor performance m...,56,Financial and schedule buffers adequately prot...,1,168,Low,3,High,4790233.60,85539.89,359,6,Threat,Cost,Concept,Construction,Band 1,Authority,Authority,Construction,RBS-580.4,2026-03-21,2026-04-30,No,Project 6,PLAN-5529,Strengthen interdisciplinary design coordination.,RESP-16425,Jennifer Simpson,BIM Coordination Process,Not Started,Conduct mandatory BIM clash detection workshop...,2026-03-01,2026-06-07,97,2026-06-07,Yes,2026-03-02,1122517.34,737844.96,65.73,RISK-1006,Related Risk Title 4,Open

In [18]:
df.columns

Index(['Record Type', 'District', 'Sub-District', 'Portfolio', 'Project',
       'Sub-Project', 'Project Name', 'BU Attributes', 'Project Status',
       'Risk ID', 'Date Raised', 'Last Review', 'Risk Title',
       'Risk Description', 'Cause', 'Effect', 'Approval Date', 'Risk Status',
       'Closed Date', 'Risk Owner', 'Progress Stage', 'RIBA Phase',
       'Current Rationale', 'Current Probability', 'Target Rationale',
       'Target Probability', 'Current Risk Score', 'Current Risk Level',
       'Target Risk Score', 'Target Risk Level', 'Current EMV', 'Target EMV',
       'Current ETV', 'Target ETV', 'Exposure', 'Driver', 'Stage',
       'Category 1', 'Current Band', 'Category 2', 'Category 3', 'Category 4',
       'RBS', 'Exposure Start', 'Exposure End', 'escalation', 'Project Name1',
       'Plan ID', 'High level Description', 'Response ID', 'Response Owner',
       'title', 'status', 'description', 'Start Date', 'Due Date',
       'Days from Due', 'Response Due', 'Completed_Closed', 'Last updated',
       'Planned Cost', 'Actual Cost', 'Percent Complete', 'Related Risk ID',
       'Risk Title.1', 'Risk Status.1'],
      dtype='object')

In [19]:
df=df[['Record Type', 'District', 'Sub-District', 'Portfolio', 'Project',
       'Sub-Project', 'Project Name', 'BU Attributes', 'Project Status',
       'Risk ID', 'Date Raised', 'Last Review', 'Risk Title',
       'Risk Description', 'Cause', 'Effect', 'Approval Date', 'Risk Status',
       'Closed Date', 'Risk Owner', 'Progress Stage', 'RIBA Phase',
       'Current Rationale', 'Current Probability', 'Target Rationale',
       'Target Probability', 'Current Risk Score', 'Current Risk Level',
       'Target Risk Score', 'Target Risk Level', 'Current EMV', 'Target EMV',
       'Current ETV', 'Target ETV', 'Exposure', 'Driver', 'Stage',
       'Category 1', 'Current Band', 'Category 2', 'Category 3', 'Category 4',
       'RBS', 'Exposure Start', 'Exposure End', 'escalation', 
       'Plan ID', 'High level Description', 'Response ID', 'Response Owner',
       'title', 'status', 'description', 'Start Date', 'Due Date',
       'Days from Due', 'Response Due', 'Completed_Closed', 'Last updated',
       'Planned Cost', 'Actual Cost', 'Percent Complete']]

In [20]:
from google.cloud import bigquery

schema = [

    # Core Identification
    bigquery.SchemaField("Record Type","STRING",mode="REQUIRED",
        description="Flag to identify the type of the Record, whehter it is a Risk, Issue, Crisis etc."),

    bigquery.SchemaField("District","STRING",mode="REQUIRED",
        description="The District under which the Project / Asset is located"),

    bigquery.SchemaField("Sub-District","STRING",mode="REQUIRED",
        description="The Sub-district under which the Project / Asset is located"),

    bigquery.SchemaField("Portfolio","STRING",mode="REQUIRED",
        description="The Portfolio to which the Project / Asset belongs to"),

    bigquery.SchemaField("Project","STRING",mode="REQUIRED",
        description="The Id of the Project. "),

    bigquery.SchemaField("Sub-Project","STRING",mode="REQUIRED",
        description="The name of the Sub-project"),

    bigquery.SchemaField("Project Name","STRING",mode="REQUIRED",
        description="The name of the Project."),

    bigquery.SchemaField("BU Attributes","STRING",mode="REQUIRED",
        description="The Business Unit to which the Asset belongs to"),

    bigquery.SchemaField("Project Status","STRING",mode="REQUIRED",
        description="The Status of the Project"),

    bigquery.SchemaField("Risk ID","STRING",mode="REQUIRED",
        description="The unique id of the Risk"),

    # Dates
    bigquery.SchemaField("Date Raised","DATE",mode="REQUIRED",
        description="The date on which the Risk was Raised"),

    bigquery.SchemaField("Last Review","DATE",mode="REQUIRED",
        description="The date on which the Risk was last reviewed"),

    bigquery.SchemaField("Approval Date","DATE",mode="REQUIRED",
        description="The date on which the Risk was Approved"),

    bigquery.SchemaField("Closed Date","DATE",mode="NULLABLE",
        description="The date on which the Risk was Closed"),

    # Risk Core
    bigquery.SchemaField("Risk Title","STRING",mode="REQUIRED",
        description="The Title of the Risk"),

    bigquery.SchemaField("Risk Description","STRING",mode="REQUIRED",
        description="The Description of the Risk"),

    bigquery.SchemaField("Cause","STRING",mode="REQUIRED",
        description="The Causes / reasons / sources that might make the Risk to materialize"),

    bigquery.SchemaField("Effect","STRING",mode="REQUIRED",
        description="The potential Effect / impact of the Risk, if it materializes"),

    bigquery.SchemaField("Risk Status","STRING",mode="REQUIRED",
        description="The current Status of the Risk"),

    bigquery.SchemaField("Risk Owner","STRING",mode="REQUIRED",
        description="The identified owner for the Risk"),

    bigquery.SchemaField("Progress Stage","STRING",mode="REQUIRED",
        description="The Stage applicable for the Risk"),

    bigquery.SchemaField("RIBA Phase","STRING",mode="REQUIRED",
        description="The RIBA phase applicable for the Risk."),

    # Risk Quantification
    bigquery.SchemaField("Current Probability","FLOAT64",mode="REQUIRED",
        description="The current Probability % of the Risk"),

    bigquery.SchemaField("Target Probability","FLOAT64",mode="REQUIRED",
        description="The Target Probability % of the Risk"),

    bigquery.SchemaField("Current Risk Score","FLOAT64",mode="REQUIRED",
        description="The Current score of the Risk"),

    bigquery.SchemaField("Target Risk Score","FLOAT64",mode="REQUIRED",
        description="The Target score of the Risk"),

    bigquery.SchemaField("Current EMV","FLOAT64",mode="REQUIRED",
        description="The current Expected Monetary Value of the impact of the Risk"),

    bigquery.SchemaField("Target EMV","FLOAT64",mode="REQUIRED",
        description="The target Expected Monetary Value of the impact of the Risk"),

    bigquery.SchemaField("Current ETV","INT64",mode="REQUIRED",
        description="The current Expected Time Value in Days"),

    bigquery.SchemaField("Target ETV","INT64",mode="REQUIRED",
        description="The target Expected Time Value in Days"),

    # Exposure & Classification
    bigquery.SchemaField("Exposure","STRING",mode="REQUIRED",
        description="The level of Exposure of the Risk"),

    bigquery.SchemaField("Driver","STRING",mode="REQUIRED",
        description="The element which drives the Risk"),

    bigquery.SchemaField("Stage","STRING",mode="REQUIRED",
        description="The construction lifecycle stage applicable for the Risk"),

    bigquery.SchemaField("Category 1","STRING",mode="REQUIRED",
        description="The Category 1 of the Risk"),

    bigquery.SchemaField("Current Band","STRING",mode="REQUIRED",
        description="The Current impact band of the Risk"),

    bigquery.SchemaField("RBS","STRING",mode="REQUIRED",
        description="The Risk Breakdown Structure code"),

    bigquery.SchemaField("Exposure Start","DATE",mode="REQUIRED",
        description="The Start date of Risk exposure"),

    bigquery.SchemaField("Exposure End","DATE",mode="REQUIRED",
        description="The End date of Risk exposure"),

    bigquery.SchemaField("escalation","STRING",mode="REQUIRED",
        description="Flag to capture escalation needed for the Risk"),


    # Response Section
    bigquery.SchemaField("Plan ID","STRING",mode="REQUIRED",
        description="The Id of the Response plan"),
     bigquery.SchemaField("High level Description","STRING",mode="REQUIRED",
        description="The high level description of the Response or Mitigation Plan"),

    bigquery.SchemaField("Response ID","STRING",mode="REQUIRED",
        description="The unique system generated Id of the Response"),

    bigquery.SchemaField("Response Owner","STRING",mode="REQUIRED",
        description="The assigned owner for the Response"),


 bigquery.SchemaField("title","STRING",mode="REQUIRED",
        description="The Title of the Response or Mitigation Plan"),

     bigquery.SchemaField("status","STRING",mode="REQUIRED",
        description="The status of the Response or Mitigation Plan"),

     bigquery.SchemaField("description","STRING",mode="REQUIRED",
        description="The detailed description of the Response or Mitigation Plan"),

    
    bigquery.SchemaField("Start Date","DATE",mode="REQUIRED",
        description="The Start date of the Response action"),

    bigquery.SchemaField("Due Date","DATE",mode="REQUIRED",
        description="The Due date of the Response action"),

    bigquery.SchemaField("Days from Due","INT64",mode="REQUIRED",
        description="Number of days until due"),

    bigquery.SchemaField("Response Due","DATE",mode="REQUIRED",
        description="The date on which the Response is due"),

    bigquery.SchemaField("Last updated","DATE",mode="REQUIRED",
        description="The date on which the Response was last updated"),

    bigquery.SchemaField("Planned Cost","FLOAT64",mode="REQUIRED",
        description="The cost planned for the Response plan"),

    bigquery.SchemaField("Actual Cost","FLOAT64",mode="REQUIRED",
        description="The cost incurred so far"),

    bigquery.SchemaField("Percent Complete","FLOAT64",mode="REQUIRED",
        description="The percentage completion of the Response plan implementation"),
]

In [152]:
client.delete_table(table_id, not_found_ok=True)

In [21]:
# df=df[['Record Type', 'District', 'Sub-District', 'Portfolio', 'Project',
#        'Sub-Project', 'Project Name', 'BU Attributes', 'Project Status',
#        'Risk ID', 'Date Raised', 'Last Review', 'Risk Title',
#        'Risk Description', 'Cause', 'Effect', 'Approval Date', 'Risk Status',
#        'Closed Date', 'Risk Owner', 'Progress Stage', 'RIBA Phase',
#        'Current Rationale', 'Current Probability', 'Target Rationale',
#        'Target Probability', 'Current Risk Score', 'Current Risk Level',
#        'Target Risk Score', 'Target Risk Level', 'Current EMV', 'Target EMV',
#        'Current ETV', 'Target ETV', 'Exposure', 'Driver', 'Stage',
#        'Category 1', 'Current Band', 'Category 2', 'Category 3', 'Category 4',
#        'RBS', 'Exposure Start', 'Exposure End', 'escalation', 
#        'Plan ID', 'High level Description', 'Response ID', 'Response Owner',
#        'title', 'status', 'description', 'Start Date', 'Due Date',
#        'Days from Due', 'Response Due', 'Completed_Closed', 'Last updated',
#        'Planned Cost', 'Actual Cost', 'Percent Complete']]

In [22]:
project_id = "prj-ai-dev-qic"
dataset_id = "qic_development"
table_id = f"{project_id}.{dataset_id}.l1_risk_data"

client = bigquery.Client(project=project_id)

job_config = bigquery.LoadJobConfig(
    schema=schema,
    write_disposition="WRITE_TRUNCATE"
)

load_job = client.load_table_from_dataframe(
    df,
    table_id,
    job_config=job_config
)

load_job.result()
print("l1_risk_data created successfully.")

l1_risk_data created successfully.

In [87]:
sql =f"SELECT * FROM `prj-qc-dev-qic.ds_dev_qic_gold_ims.l1_maintable`"
df = bq_client.query_and_wait(sql).to_dataframe(create_bqstorage_client=False)

In [88]:
df.columns

Index(['Activity ID', 'Project Number', 'Project ID', 'Prog Version',
       'Activity Number', 'Activity Name', 'Activity Type', 'Activity Status',
       'District', 'Development', 'Class L1 V2', 'Class L2 V2', 'Class L3 V2',
       'Stage Gate L1', 'Stage Gate L2 V1', 'Stage Gate L2 V2', 'Asset',
       'Project Status', 'Phase', 'Business Class', 'Precinct', 'Core Assets',
       'Start Date', 'End Date', 'SG-Summary', 'QIC-BOD PC', 'QIC-BOD PC-Date',
       'QIC-BOD-ML-ID', 'QIC-BOD-ML-DES', 'QIC-BOD-ML-Date'],
      dtype='object')

In [89]:
df=df[ [
    "Activity ID",
    "Project ID",
    "Prog Version",
    "Activity Name",
    "Activity Type",
    "Activity Status",
    "District",
    "Development",
    "Class L1 V2",
    "Class L2 V2",
    "Asset",
    "Project Status",
    'Stage Gate L1', 
    'Stage Gate L2 V1',
    "Phase",
    "Business Class",
    "Precinct",
    "Core Assets",
    "Start Date",
    "End Date",
    "SG-Summary",
    "QIC-BOD PC",
    "QIC-BOD PC-Date",
    "QIC-BOD-ML-ID",
    "QIC-BOD-ML-DES",
    "QIC-BOD-ML-Date"
]]

In [90]:
df.columns = ['Activity ID', 'Project ID', 'Prog Version', 'Activity Name',
       'Activity Type', 'Activity Status', 'District', 'Development',
       'Class L1 ID', 'Class L2 ID', 'Asset', 'Project Status',
       'Stage Gate L1 ID', 'Stage Gate L2 ID', 'Phase', 'Business Class',
       'Precinct', 'Core Assets', 'Start Date', 'End Date', 'SG-Summary',
       'QIC-BOD PC', 'QIC-BOD PC-Date', 'QIC-BOD-ML-ID', 'QIC-BOD-ML-DES',
       'QIC-BOD-ML-Date']

In [93]:
df=df.sample(50)

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 44880 to 126575
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Activity ID       50 non-null     object
 1   Project ID        50 non-null     object
 2   Prog Version      50 non-null     object
 3   Activity Name     50 non-null     object
 4   Activity Type     50 non-null     object
 5   Activity Status   50 non-null     object
 6   District          45 non-null     Int64
 7   Development       45 non-null     Int64
 8   Class L1 ID       24 non-null     Int64
 9   Class L2 ID       24 non-null     Int64
 10  Asset             44 non-null     Int64
 11  Project Status    23 non-null     Int64
 12  Stage Gate L1 ID  44 non-null     Int64
 13  Stage Gate L2 ID  25 non-null     Int64
 14  Phase             21 non-null     Int64
 15  Business Class    41 non-null     Int64
 16  Precinct          15 non-null     Int64
 17  Core Assets       37 non-null     Int64
 18  Start Date        50 non-null     datetime64[us, UTC]
 19  End Date          50 non-null     datetime64[us, UTC]
 20  SG-Summary        50 non-null     object
 21  QIC-BOD PC        0 non-null      object
 22  QIC-BOD PC-Date   0 non-null      datetime64[us, UTC]
 23  QIC-BOD-ML-ID     0 non-null      object
 24  QIC-BOD-ML-DES    0 non-null      object
 25  QIC-BOD-ML-Date   0 non-null      datetime64[us, UTC]
dtypes: Int64(12), datetime64[us, UTC](4), object(10)
memory usage: 11.1+ KB

In [98]:
# Remove timezone from all datetime columns
for col in df.select_dtypes(include=["datetimetz"]).columns:
    df[col] = df[col].dt.tz_localize(None)

# Now export
df.head(10).to_excel("data/test.xlsx", index=False)

In [100]:
df.head()

,Activity ID,Project ID,Prog Version,Activity Name,Activity Type,Activity Status,District,Development,Class L1 ID,Class L2 ID,Asset,Project Status,Stage Gate L1 ID,Stage Gate L2 ID,Phase,Business Class,Precinct,Core Assets,Start Date,End Date,SG-Summary,QIC-BOD PC,QIC-BOD PC-Date,QIC-BOD-ML-ID,QIC-BOD-ML-DES,QIC-BOD-ML-Date
44880,D13-LPR-1304-17340,IMS-D13-2026-01-FC-001.00,Current,Summary - Cost Plan (2.E),TT_Task,TK_NotStart,37475,75770,289428,293653,147855,256836,75825,<NA>,75979,145767,<NA>,<NA>,2028-06-28 07:00:00,2028-11-28 18:00:00,non SG-Summary,None,NaT,None,None,NaT
108874,D05-WRPB-SG3-3F-900,IMS-S&R-2025-03-BL-001.00,BL,Cost Plan (3.F),TT_Task,TK_NotStart,38239,75771,<NA>,<NA>,144041,<NA>,75834,75902,<NA>,<NA>,<NA>,75769,2029-06-25 07:00:00,2029-07-22 18:00:00,non SG-Summary,None,NaT,None,None,NaT
79537,D11-EDU-1102-10150,IMS-D11-2024-12-BL-001.00,BL,Summary - Feasibility Model (2.B),TT_Task,TK_NotStart,38241,75771,<NA>,<NA>,108126,<NA>,75833,75893,<NA>,145767,<NA>,75769,2025-02-16 08:00:00,2025-02-16 08:00:00,non SG-Summary,None,NaT,None,None,NaT
178703,D18-RES-057-P11-1560,IMS-D18-PH2-2026-01-FC-001.00,Current,Summary - Legal Report (2.L),TT_Task,TK_NotStart,79108,75771,293641,295888,257098,295882,295545,<NA>,82603,145229,<NA>,75769,2042-06-08 07:00:00,2042-06-24 18:00:00,non SG-Summary,None,NaT,None,None,NaT
131801,D05-MOT-AD0017-SG4-106,IMS-D05-2026-01-FC-001.NA,Current,Summary - Concept Design Report - Interior (4.B),TT_Task,TK_NotStart,38239,75771,297445,297446,297465,295882,75835,76020,<NA>,145232,<NA>,17774,2034-11-06 07:00:00,2035-01-24 18:00:00,non SG-Summary,None,NaT,None,None,NaT

In [154]:
df = pd.read_excel("data/l1_time_maintable_sample_v2.xlsx")

In [155]:
df.shape

(100, 29)

In [157]:
from google.cloud import bigquery

schema = [

    # Identification
    bigquery.SchemaField("Activity ID","STRING",mode="REQUIRED",
        description="The unique user specified id for each Activity in a Project (Unique within a Project)"),

    bigquery.SchemaField("Project ID","STRING",mode="REQUIRED",
        description="The unique user specified number for each Project / Schedule"),

    bigquery.SchemaField("Programme version","STRING",mode="REQUIRED",
        description="A flag to specify whether the project is a Pre-work or for Actual Construction or Any other"),

    bigquery.SchemaField("Activity Name","STRING",mode="REQUIRED",
        description="The user specified Name for each Activity in the system"),

    bigquery.SchemaField("Activity Type","STRING",mode="REQUIRED",
        description="The user selected Activity Type which qualifies whether the Activity is Task dependent or Resource dependent or Milestone etc."),

    bigquery.SchemaField("Activity Status","STRING",mode="REQUIRED",
        description="The Status of the Activity in the Project, which will be Not Started, Active or Completed"),

    # Qiddiya Code Fields
    bigquery.SchemaField("Qiddiya - District ID","STRING",mode="REQUIRED",
        description="The District under which the Asset represented in the Activity is located"),

    bigquery.SchemaField("Qiddiya - Development ID","STRING",mode="REQUIRED",
        description="The Development id which the Asset represented in the Activity is tagged to"),

    bigquery.SchemaField("Qiddiya - Class L1 ID","STRING",mode="REQUIRED",
        description="The Asset Class Level 1 id of the Asset represented in the Activity"),

    bigquery.SchemaField("Qiddiya - Class L2 ID","STRING",mode="REQUIRED",
        description="The Asset Class Level 2 id of the Asset represented in the Activity"),

    bigquery.SchemaField("Qiddiya - Asset ID","STRING",mode="REQUIRED",
        description="The unique id for the Asset which is represented in the Activity"),

    bigquery.SchemaField("Qiddiya - Stage Gate Level 1 ID","STRING",mode="REQUIRED",
        description="The id of the Stage Gate Level 1 of the Asset represented in the Activity"),

    bigquery.SchemaField("Qiddiya - Stage Gate Level 2 ID","STRING",mode="REQUIRED",
        description="The id of the Stage Gate Level 2 of the Asset represented in the Activity"),

    bigquery.SchemaField("Qiddiya - Phase ID","STRING",mode="REQUIRED",
        description="The construction phase in which the Asset represented in the Activity is at present"),

    bigquery.SchemaField("Qiddiya - Business Class ID","STRING",mode="REQUIRED",
        description="The Business Unit to which the Asset represented in the Activity belongs"),

    bigquery.SchemaField("Qiddiya - Precinct ID","STRING",mode="REQUIRED",
        description="The Precinct under which the Asset represented in the Activity is located"),

    bigquery.SchemaField("Qiddiya - Core Assets ID","STRING",mode="REQUIRED",
        description="Flag to specify whether the Asset represented in the Activity is a Core Asset or Non-core Asset"),

    # Schedule Dates
    bigquery.SchemaField("Actual Start Date","DATE",mode="NULLABLE",
        description="The Actual date on which Work started for the Activity"),

    bigquery.SchemaField("Actual End Date","DATE",mode="NULLABLE",
        description="The Actual date on which Work ended for the Activity"),

    bigquery.SchemaField("Early Start Date","DATE",mode="REQUIRED",
        description="The possible Early Start date for the Activity as per the latest schedule"),

    bigquery.SchemaField("Early End Date","DATE",mode="REQUIRED",
        description="The possible Early End date for the Activity as per the latest schedule"),

    bigquery.SchemaField("Start","DATE",mode="REQUIRED",
        description="The Scheduled Start date for the Activity as per the latest schedule"),

    bigquery.SchemaField("Finish","DATE",mode="REQUIRED",
        description="The Scheduled Finish date for the Activity as per the latest schedule"),

    # Stage Gate / Board Reporting
    bigquery.SchemaField("SG-Summary","STRING",mode="NULLABLE",
        description="User entered Stage Gate summary details for the Asset represented in the Activity"),

    bigquery.SchemaField("QIC-BOD PC","FLOAT64",mode="NULLABLE",
        description="User entered Percentage Completion number for the Asset represented in the Activity, presented to the Board of Directors"),

    bigquery.SchemaField("QIC-BOD PC-Date","DATE",mode="NULLABLE",
        description="User entered Percentage Completion date presented to the Board of Directors"),

    bigquery.SchemaField("QIC-BOD-ML-ID","STRING",mode="NULLABLE",
        description="User entered Milestone Id presented to the Board of Directors"),

    bigquery.SchemaField("QIC-BOD-ML-DES","STRING",mode="NULLABLE",
        description="User entered Milestone Description presented to the Board of Directors"),

    bigquery.SchemaField("QIC-BOD-ML-Date","DATE",mode="NULLABLE",
        description="User entered Milestone Date presented to the Board of Directors"),
]

In [158]:
project_id = "prj-ai-dev-qic"
dataset_id = "qic_development"
table_id = f"{project_id}.{dataset_id}.l1_time_data"

client = bigquery.Client(project=project_id)

job_config = bigquery.LoadJobConfig(
    schema=schema,
    write_disposition="WRITE_TRUNCATE"
)

load_job = client.load_table_from_dataframe(
    df,
    table_id,
    job_config=job_config
)

load_job.result()

print("l1_time_data created successfully.")

l1_time_data created successfully.

In [110]:
sql =f"SELECT * FROM `prj-qc-dev-qic.ds_dev_qic_gold_cost.l3_financial_commercial_cost_breakdown`"
df = bq_client.query_and_wait(sql).to_dataframe(create_bqstorage_client=False)

In [111]:
df=df[[
    "PROJ_ACCOUNT",
    "PRISM Project ID",
    "Baseline Budget",
    "Budget Change",
    "Approved Budget",
    "EAC",
    "TDC",
    "District",
    "Project",
    "Location",
    "Business Unit",
    "Total Commitment",
    "VR_BoardApproved_Budget",
    "TDC Approved Budget",
    "Original Contract Value SAR",
    "Revised Contract Value SAR",
    "Approved AVIs"
]]

In [112]:
df.head()

,PROJ_ACCOUNT,PRISM Project ID,Baseline Budget,Budget Change,Approved Budget,EAC,TDC,District,Project,Location,Business Unit,Total Commitment,VR_BoardApproved_Budget,TDC Approved Budget,Original Contract Value SAR,Revised Contract Value SAR,Approved AVIs
0,P01.QC.02.001.324.D.410.0000000000,P01,5073750.000000000,-5073750.000000000,0E-9,0E-9,0E-9,District 12 - Resort Core,001 Six Flags Qiddiya,Lower Plateau,Entertainment,0E-9,5073750.000000000,5073750.000000000,None,None,None
1,P01.QC.02.001.000.G.900.0000000000,P01,146250000.000000000,-99234750.000000000,47015250.000000000,47015250.000000000,0E-9,District 12 - Resort Core,001 Six Flags Qiddiya,Lower Plateau,Entertainment,0E-9,146250000.000000000,146250000.000000000,None,None,None
2,P01.QC.02.001.000.H.916.0000000000,P01,215400000.000000000,-245275.150000000,215154724.840000000,215154724.840000000,0E-9,District 12 - Resort Core,001 Six Flags Qiddiya,Lower Plateau,Entertainment,336328920.000000000,215400000.000000000,215400000.000000000,None,None,None
3,P01.QC.02.001.200.D.227.0000000000,P01,139492318.000000000,-139492318.000000000,0E-9,0E-9,0E-9,District 12 - Resort Core,001 Six Flags Qiddiya,Lower Plateau,Entertainment,0E-9,139492318.000000000,139492318.000000000,None,None,None
4,P01.QC.02.001.200.D.330.0000000000,P01,151663725.300000000,-151663725.300000000,0E-9,0E-9,0E-9,District 12 - Resort Core,001 Six Flags Qiddiya,Lower Plateau,Entertainment,0E-9,151663725.300000000,151663725.300000000,None,None,None

In [113]:
df.shape

(8764, 17)

In [115]:
df.head(10).to_excel("data/test.xlsx", index=False)

In [159]:
df = pd.read_excel("data/l1_cost_sample_dataset.xlsx")

In [161]:
from google.cloud import bigquery

schema = [

    # Identification
    bigquery.SchemaField(
        "PROJ_ACCOUNT",
        "STRING",
        mode="REQUIRED",
        description="The Project level Account Number against which the financials are captured, consolidated and tracked in Prism"
    ),

    bigquery.SchemaField(
        "PRISM Project ID",
        "STRING",
        mode="REQUIRED",
        description="The id created and managed in Prism for the Project. This may be different from the Project ids used in other systems like P6, ARM and SAP"
    ),

    # Budget Fields
    bigquery.SchemaField(
        "Baseline Budget",
        "FLOAT64",
        mode="REQUIRED",
        description="The baseline budget for the Project / Asset"
    ),

    bigquery.SchemaField(
        "Budget Change",
        "FLOAT64",
        mode="REQUIRED",
        description="The total changes made to the Budget"
    ),

    bigquery.SchemaField(
        "Approved Budget",
        "FLOAT64",
        mode="REQUIRED",
        description="The current Approved budget for the Project / Asset. This is the sum of Baseline Budget + Budget Change"
    ),

    bigquery.SchemaField(
        "EAC",
        "FLOAT64",
        mode="REQUIRED",
        description="Estimate At Completion. Represents the Estimated cost of the Project / Asset at the time of completion"
    ),

    bigquery.SchemaField(
        "TDC",
        "FLOAT64",
        mode="REQUIRED",
        description="Total Delivered Cost representing the actual cost delivered to date"
    ),

    # Project Attributes
    bigquery.SchemaField(
        "District",
        "STRING",
        mode="REQUIRED",
        description="The name of the District under which the particular Project / Asset is located"
    ),

    bigquery.SchemaField(
        "Project",
        "STRING",
        mode="REQUIRED",
        description="The name of the Project in Prism. This may be different from the Project names used in other systems like P6, ARM and SAP"
    ),

    bigquery.SchemaField(
        "Location",
        "STRING",
        mode="REQUIRED",
        description="The location of the Project / Asset"
    ),

    bigquery.SchemaField(
        "Business Unit",
        "STRING",
        mode="REQUIRED",
        description="The name of the Business Unit to which the particular Project / Asset belongs to"
    ),

    # Financial Controls
    bigquery.SchemaField(
        "Total Commitment",
        "FLOAT64",
        mode="REQUIRED",
        description="The Total commitment made for the Project. Sum of all approved Purchase Orders for the Project"
    ),

    bigquery.SchemaField(
        "VR_BoardApproved_Budget",
        "FLOAT64",
        mode="REQUIRED",
        description="The Budget approved by the Board"
    ),

    bigquery.SchemaField(
        "TDC Approved Budget",
        "FLOAT64",
        mode="REQUIRED",
        description="The approved Total Delivered Cost budget limit"
    ),

    # Contract Values
    bigquery.SchemaField(
        "Original Contract Value SAR",
        "FLOAT64",
        mode="REQUIRED",
        description="Original Contract Value in Saudi Riyal"
    ),

    bigquery.SchemaField(
        "Revised Contract Value SAR",
        "FLOAT64",
        mode="REQUIRED",
        description="Revised Contract Value in Saudi Riyal"
    ),

    bigquery.SchemaField(
        "Approved AVIs",
        "FLOAT64",
        mode="REQUIRED",
        description="Approved variations / changes for the Contract. AVI means Agreed Value of Instruction"
    ),
]

In [162]:
project_id = "prj-ai-dev-qic"
dataset_id = "qic_development"
table_id = f"{project_id}.{dataset_id}.l1_cost_breakdown"
client.delete_table(table_id, not_found_ok=True)

In [163]:
project_id = "prj-ai-dev-qic"
dataset_id = "qic_development"
table_id = f"{project_id}.{dataset_id}.l1_cost_breakdown_data"

client = bigquery.Client(project=project_id)

job_config = bigquery.LoadJobConfig(
    schema=schema,
    write_disposition="WRITE_TRUNCATE"
)

load_job = client.load_table_from_dataframe(
    df,
    table_id,
    job_config=job_config
)

load_job.result()

print("l1_cost_breakdown_data created successfully.")

l1_cost_breakdown_data created successfully.

In [119]:
df = pd.read_excel("data/Development_Cost_Timephased_Sample.xlsx")

In [126]:
from google.cloud import bigquery

schema = [

    bigquery.SchemaField(
        "PROJ_ACCOUNT",
        "STRING",
        mode="REQUIRED",
        description="The Account Number against which the financials are captured, consolidated and tracked in Prism"
    ),

    bigquery.SchemaField(
        "Control Account",
        "STRING",
        mode="REQUIRED",
        description="The account against which financial transactions are made. Control Accounts are created under a Project in Prism"
    ),

    bigquery.SchemaField(
        "Work Performed",
        "STRING",
        mode="REQUIRED",
        description="A calculated value representing the quantum of work performed for the Project / Asset"
    ),

    bigquery.SchemaField(
        "Account Phase",
        "INT64",
        mode="REQUIRED",
        description="The phase in which the Project / Asset is currently. It is a 3 digit numerical code (eg. 124, 125, 610..), with each code representing a different phase"
    ),

    bigquery.SchemaField(
        "Period Label",
        "DATE",
        mode="REQUIRED",
        description="The Date of the Financial period in which the transaction is made. Qiddiya follows Monthy period for financial purposes"
    ),

    bigquery.SchemaField(
        "A_Actual",
        "FLOAT64",
        mode="REQUIRED",
        description="The Actual financial value updated for each transaction, for that particular period"
    ),

    bigquery.SchemaField(
        "Forecast",
        "FLOAT64",
        mode="REQUIRED",
        description="The Forecasted financial value for each transaction, for that particular period"
    ),

]

In [125]:
phase_map = {
    "Design": 124,
    "Procurement": 125,
    "Construction": 610,
    "Testing & Commissioning": 720
}

df["Account Phase"] = df["Account Phase"].map(phase_map)
df["Account Phase"] = df["Account Phase"].astype("Int64")

In [128]:
import pandas as pd

# Convert Period Label to proper month-end date
df["Period Label"] = pd.to_datetime(
    df["Period Label"],
    format="%b-%Y"
)

# Optional: if you want month-end explicitly
df["Period Label"] = df["Period Label"] + pd.offsets.MonthEnd(0)

# Ensure correct dtype
df["Period Label"] = df["Period Label"].dt.date

In [129]:
project_id = "prj-ai-dev-qic"
dataset_id = "qic_development"
table_id = f"{project_id}.{dataset_id}.l1_tpd_actuals"

client = bigquery.Client(project=project_id)

job_config = bigquery.LoadJobConfig(
    schema=schema,
    write_disposition="WRITE_TRUNCATE"
)

load_job = client.load_table_from_dataframe(
    df,
    table_id,
    job_config=job_config
)

load_job.result()

print("l1_tpd_actuals created successfully.")

l1_tpd_actuals created successfully.

In [1]:


from google.cloud import bigquery

# ─────────────────────────────────────────────
# CONFIG — update these values
# ─────────────────────────────────────────────
PROJECT_ID   = "prj-ai-dev-qic"
DATASET_ID   = "qic_hr"
TABLE_ID     = "dim_department"
client = bigquery.Client(project=PROJECT_ID)
# New table-level description (set to None to leave unchanged)
NEW_TABLE_DESCRIPTION = "This table stores hr data"

# Map of column_name → new description.
# Only listed columns will be updated; all others are left as-is.
COLUMN_DESCRIPTIONS = {
    "Department_ID":   "Department ID",
    "Department_Name":   "Department Name",
    "Parent_Department_ID": "Parent Department ID",
}
# ─────────────────────────────────────────────


def update_descriptions(
    project: str,
    dataset: str,
    table: str,
    table_desc: str | None,
    column_descs: dict[str, str],
) -> None:
    
    table_ref = f"{project}.{dataset}.{table}"

    # 1. Fetch the existing table object (full schema preserved)
    bq_table = client.get_table(table_ref)
    print(f"✅ Fetched table: {table_ref}")
    print(f"   Rows: {bq_table.num_rows:,}  |  Columns: {len(bq_table.schema)}")

    # 2. Rebuild schema — only touch descriptions, nothing else
    new_schema = []
    for field in bq_table.schema:
        if field.name in column_descs:
            # Reconstruct the field with the new description, keeping everything else
            updated_field = bigquery.SchemaField(
                name        = field.name,
                field_type  = field.field_type,
                mode        = field.mode,
                description = column_descs[field.name],
                fields      = field.fields,           # preserves nested/repeated fields
                precision   = field.precision,
                scale       = field.scale,
                max_length  = field.max_length,
            )
            new_schema.append(updated_field)
            print(f"   📝 Updated column: {field.name}")
        else:
            new_schema.append(field)                  # no change

    # 3. Apply schema update
    bq_table.schema = new_schema

    # 4. Update table description if provided
    fields_to_update = ["schema"]
    if table_desc is not None:
        bq_table.description = table_desc
        fields_to_update.append("description")
        print(f"   📝 Updated table description")

    # 5. Patch the table (only schema + description fields are touched)
    client.update_table(bq_table, fields_to_update)
    print(f"\n✅ Done — table updated successfully: {table_ref}")


update_descriptions(
    project     = PROJECT_ID,
    dataset     = DATASET_ID,
    table       = TABLE_ID,
    table_desc  = NEW_TABLE_DESCRIPTION,
    column_descs= COLUMN_DESCRIPTIONS,
)

✅ Fetched table: prj-ai-dev-qic.qic_hr.dim_department
   Rows: 4  |  Columns: 7
   📝 Updated column: Department_ID
   📝 Updated column: Department_Name
   📝 Updated column: Parent_Department_ID
   📝 Updated table description

✅ Done — table updated successfully: prj-ai-dev-qic.qic_hr.dim_department

In [6]:
table_ref = f"{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}"
bq_table = client.get_table(table_ref)
print("Table description:", bq_table.description)
for field in bq_table.schema:
    print(f"  {field.name}: {field.description}")

Table description: This table stores hr data
  Department_ID: Department ID
  Department_Name: Department Name
  Parent_Department_ID: Parent Department ID
  Business_Unit: None
  Is_Active: None
  Cost_Center_ID: None
  VP_Name: None